[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "plugins/_version.py"

[project]
name = "plugins"
dynamic = ["version"]
description = "Internal plugins for SeqGen."
requires-python = ">=3.8"
dependencies = [
    "seqgen", # Resolved from workspace
]

[tool.hatch.build.targets.wheel]
packages = ["plugins"]

[tool.hatch.build.targets.sdist]
include = [
    "plugins/**",
    "pyproject.toml",
]
